services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - db
      - maildev
    develop:
      watch:
        - action: sync
          path: ./
          target: /app/
          ignore:
            - .venv/
        - action: rebuild
          path: pyproject.toml

  pytest-watch:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ptw
    restart: always
    depends_on:
      - db
      - maildev
    develop:
      watch:
        - action: sync
          path: ./
          target: /app/
          ignore:
            - .venv/
        - action: rebuild
          path: pyproject.toml

  db:
    image: postgres:16-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: simple_blog
    volumes:
      - db-data:/var/lib/postgresql/data

  maildev:
    image: maildev/maildev
    restart: always
    ports:
      - 1080:1080

volumes:
  db-data:
