services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    depends_on:
      - app
    volumes:
      - media-files:/var/www/media:ro

  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: always
    env_file:
      - .env.production
    depends_on:
      - db
      - maildev
    volumes:
      - media-files:/app/media

  db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: simple_blog
    volumes:
      - db-data:/var/lib/postgresql/data

  maildev:
    image: maildev/maildev
    restart: always

volumes:
  db-data:
  media-files:
